"""create table train_item_praat_feedback

Revision ID: 0c92f649869c
Revises: b3a46b4392a0
Create Date: 2025-11-13 13:52:09.702227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0c92f649869c'
down_revision: Union[str, Sequence[str], None] = 'b3a46b4392a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_item_praat_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('praat_features_id', sa.Integer(), nullable=False),
    sa.Column('vowel_distortion_feedback', sa.Text(), nullable=True),
    sa.Column('sound_stability_feedback', sa.Text(), nullable=True),
    sa.Column('voice_clarity_feedback', sa.Text(), nullable=True),
    sa.Column('voice_health_feedback', sa.Text(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_item_praat_feedback_praat_features_id'), 'train_item_praat_feedback', ['praat_features_id'], unique=False)
    op.create_table('train_session_praat_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_praat_result_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_session_praat_feedback_session_praat_result_id'), 'train_session_praat_feedback', ['session_praat_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_session_praat_feedback_session_praat_result_id'), table_name='train_session_praat_feedback')
    op.drop_table('train_session_praat_feedback')
    op.drop_index(op.f('ix_train_item_praat_feedback_praat_features_id'), table_name='train_item_praat_feedback')
    op.drop_table('train_item_praat_feedback')
    # ### end Alembic commands ###
