"""praat_session-filed_update

Revision ID: 1852e5e760f0
Revises: ee11e5714e83
Create Date: 2025-11-09 11:25:14.728759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1852e5e760f0'
down_revision: Union[str, Sequence[str], None] = 'ee11e5714e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_praat_results', sa.Column('avg_cpp', sa.Float(), nullable=True))
    op.add_column('session_praat_results', sa.Column('avg_csid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_praat_results', 'avg_csid')
    op.drop_column('session_praat_results', 'avg_cpp')
    # ### end Alembic commands ###
