"""train_sentence relation 제거

Revision ID: 1d25f98e2b22
Revises: a2725743b1d5
Create Date: 2025-10-23 17:31:28.278419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1d25f98e2b22'
down_revision: Union[str, Sequence[str], None] = 'a2725743b1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_results', sa.Column('train_words_id', sa.Integer(), nullable=True))
    op.add_column('train_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('train_sentences', 'train_words_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_sentences', sa.Column('train_words_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('train_results', 'user_id')
    op.drop_column('train_results', 'train_words_id')
    # ### end Alembic commands ###
