"""upgrade_user_table_second

Revision ID: 20fd52cf7b3b
Revises: e8f57ca4c4e0
Create Date: 2025-10-24 10:08:54.260138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '20fd52cf7b3b'
down_revision: Union[str, Sequence[str], None] = 'e8f57ca4c4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sqlmodel.sql.sqltypes.AutoString(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
