"""training_item에 image_url 추가

Revision ID: 2833868e6b0f
Revises: 9b4a2934a8b3
Create Date: 2025-11-07 08:50:36.370614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2833868e6b0f'
down_revision: Union[str, Sequence[str], None] = '9b4a2934a8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_items', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_items', 'image_url')
    # ### end Alembic commands ###
