"""add user voice

Revision ID: 3a31b0974d05
Revises: 1852e5e760f0
Create Date: 2025-11-09 15:01:28.461393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3a31b0974d05'
down_revision: Union[str, Sequence[str], None] = '1852e5e760f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('source_audio_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_voice_user_id'), 'user_voice', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_voice_voice_id'), 'user_voice', ['voice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_voice_voice_id'), table_name='user_voice')
    op.drop_index(op.f('ix_user_voice_user_id'), table_name='user_voice')
    op.drop_table('user_voice')
    # ### end Alembic commands ###
