"""train_sentence relation 제거

Revision ID: 3d5ed6e2b25d
Revises: 1d25f98e2b22
Create Date: 2025-10-23 17:34:18.462714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3d5ed6e2b25d'
down_revision: Union[str, Sequence[str], None] = '1d25f98e2b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
