"""

Revision ID: 40976aba46d9
Revises: 3ff56b5bd323
Create Date: 2025-10-23 14:30:41.167916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '40976aba46d9'
down_revision: Union[str, Sequence[str], None] = '3ff56b5bd323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train_results', 'train_sentences_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'train_results', 'train_sentences', ['train_sentences_id'], ['id'])
    op.alter_column('train_sentences', 'train_words_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'train_sentences', 'train_words', ['train_words_id'], ['id'])
    op.create_index(op.f('ix_train_words_word'), 'train_words', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_words_word'), table_name='train_words')
    op.drop_constraint(None, 'train_sentences', type_='foreignkey')
    op.alter_column('train_sentences', 'train_words_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'train_results', type_='foreignkey')
    op.alter_column('train_results', 'train_sentences_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
