"""unified_training_sessions

Revision ID: 51f296d63302
Revises: 1f92da36b4a0
Create Date: 2025-10-24 22:46:41.738339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '51f296d63302'
down_revision: Union[str, Sequence[str], None] = '1f92da36b4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 먼저 nullable=True로 컬럼들을 추가
    op.add_column('training_sessions', sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_sessions', sa.Column('training_date', sa.DateTime(), nullable=True))
    op.add_column('training_sessions', sa.Column('progress_percentage', sa.Float(), nullable=True))
    op.add_column('training_sessions', sa.Column('session_metadata', sa.JSON(), nullable=True))
    op.add_column('training_sessions', sa.Column('started_at', sa.DateTime(), nullable=True))
    
    # 기존 데이터에 기본값 설정
    op.execute("UPDATE training_sessions SET session_name = '기본 세션' WHERE session_name IS NULL")
    op.execute("UPDATE training_sessions SET training_date = created_at WHERE training_date IS NULL")
    op.execute("UPDATE training_sessions SET progress_percentage = 0.0 WHERE progress_percentage IS NULL")
    op.execute("UPDATE training_sessions SET session_metadata = '{}' WHERE session_metadata IS NULL")
    
    # 이제 NOT NULL로 변경
    op.alter_column('training_sessions', 'session_name', nullable=False)
    op.alter_column('training_sessions', 'training_date', nullable=False)
    op.alter_column('training_sessions', 'progress_percentage', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'started_at')
    op.drop_column('training_sessions', 'session_metadata')
    op.drop_column('training_sessions', 'progress_percentage')
    op.drop_column('training_sessions', 'training_date')
    op.drop_column('training_sessions', 'session_name')
    # ### end Alembic commands ###
