"""training-session_training_item_table_refactor

Revision ID: 588ac1995097
Revises: 3a5caa26a583
Create Date: 2025-10-31 13:29:36.526780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '588ac1995097'
down_revision: Union[str, Sequence[str], None] = '3a5caa26a583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_items', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('training_items', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('training_sessions', sa.Column('average_score', sa.Float(), nullable=True))
    op.add_column('training_sessions', sa.Column('overall_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'overall_feedback')
    op.drop_column('training_sessions', 'average_score')
    op.drop_column('training_items', 'feedback')
    op.drop_column('training_items', 'score')
    # ### end Alembic commands ###
