"""발화 훈련 진행 상태 관련 테이블 단어/문장으로 분리

Revision ID: 793880e8f7d2
Revises: 15d52b0255e2
Create Date: 2025-10-24 19:54:21.197427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '793880e8f7d2'
down_revision: Union[str, Sequence[str], None] = '15d52b0255e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_training_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_training_session_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_recorded', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_training_items_sentence_training_session_id'), 'sentence_training_items', ['sentence_training_session_id'], unique=False)
    op.create_table('sentence_training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='sentencetrainingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_training_sessions_user_id'), 'sentence_training_sessions', ['user_id'], unique=False)
    op.create_table('word_training_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_training_session_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_recorded', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_training_items_word_training_session_id'), 'word_training_items', ['word_training_session_id'], unique=False)
    op.create_table('word_training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='wordtrainingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_training_sessions_user_id'), 'word_training_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_training_items_training_session_id'), table_name='training_items')
    op.drop_table('training_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('training_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', postgresql.ENUM('WORD', 'SENTENCE', name='itemtype'), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sequence_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_recorded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('video_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('training_items_pkey'))
    )
    op.create_index(op.f('ix_training_items_training_session_id'), 'training_items', ['training_session_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('training_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='trainingstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('training_sessions_pkey'))
    )
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_word_training_sessions_user_id'), table_name='word_training_sessions')
    op.drop_table('word_training_sessions')
    op.drop_index(op.f('ix_word_training_items_word_training_session_id'), table_name='word_training_items')
    op.drop_table('word_training_items')
    op.drop_index(op.f('ix_sentence_training_sessions_user_id'), table_name='sentence_training_sessions')
    op.drop_table('sentence_training_sessions')
    op.drop_index(op.f('ix_sentence_training_items_sentence_training_session_id'), table_name='sentence_training_items')
    op.drop_table('sentence_training_items')
    # ### end Alembic commands ###
