"""Remove physical FK from MediaFile and add logical FK with Relationship

Revision ID: 81733ecc8c91
Revises: e8375b494fbf
Create Date: 2025-10-25 11:01:30.290948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '81733ecc8c91'
down_revision: Union[str, Sequence[str], None] = 'e8375b494fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('media_files_user_id_fkey'), 'media_files', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('media_files_user_id_fkey'), 'media_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
