"""praat_model_second

Revision ID: 961f1fe7b110
Revises: a1655bf9ffd7
Create Date: 2025-10-29 12:39:10.124301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '961f1fe7b110'
down_revision: Union[str, Sequence[str], None] = 'a1655bf9ffd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('praat_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('jitter_local', sa.Float(), nullable=True),
    sa.Column('shimmer_local', sa.Float(), nullable=True),
    sa.Column('hnr', sa.Float(), nullable=True),
    sa.Column('nhr', sa.Float(), nullable=True),
    sa.Column('f0', sa.Float(), nullable=True),
    sa.Column('max_f0', sa.Float(), nullable=True),
    sa.Column('min_f0', sa.Float(), nullable=True),
    sa.Column('cpp', sa.Float(), nullable=True),
    sa.Column('csid', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_praat_features_media_id'), 'praat_features', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_praat_features_media_id'), table_name='praat_features')
    op.drop_table('praat_features')
    # ### end Alembic commands ###
