"""training_item에 audio_url 추가

Revision ID: 9b4a2934a8b3
Revises: 489fa60b451f
Create Date: 2025-11-06 15:09:55.453846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9b4a2934a8b3'
down_revision: Union[str, Sequence[str], None] = '489fa60b451f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_items', sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_items', 'audio_url')
    # ### end Alembic commands ###
