"""update user voice

Revision ID: 9e0ead94f2f3
Revises: 3a31b0974d05
Create Date: 2025-11-09 15:13:59.789158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9e0ead94f2f3'
down_revision: Union[str, Sequence[str], None] = '3a31b0974d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_voice_user_id_fkey'), 'user_voice', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_voice_user_id_fkey'), 'user_voice', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
