"""user_model_fix

Revision ID: a5f3af8a40d8
Revises: d8fcc10502fd
Create Date: 2025-10-27 14:40:38.224440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a5f3af8a40d8'
down_revision: Union[str, Sequence[str], None] = 'd8fcc10502fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('users', 'gender')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
