"""Add media_file_id to training_items

Revision ID: b1f9b80fc915
Revises: 1434c000f464
Create Date: 2025-10-25 11:18:36.620210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b1f9b80fc915'
down_revision: Union[str, Sequence[str], None] = '1434c000f464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_items', sa.Column('media_file_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_items', 'media_file_id')
    # ### end Alembic commands ###
