"""init

Revision ID: b249ba5637cf
Revises: 
Create Date: 2025-11-14 11:37:07.223861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b249ba5637cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_session_praat_feedback', sa.Column('ai_model_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_train_session_praat_feedback_ai_model_id'), 'train_session_praat_feedback', ['ai_model_id'], unique=False)
    op.drop_column('train_session_praat_feedback', 'model_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_session_praat_feedback', sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_train_session_praat_feedback_ai_model_id'), table_name='train_session_praat_feedback')
    op.drop_column('train_session_praat_feedback', 'ai_model_id')
    # ### end Alembic commands ###
