"""alter table add column

Revision ID: c064937e2ae0
Revises: 98cacd8f2408
Create Date: 2025-11-19 10:18:43.015080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c064937e2ae0'
down_revision: Union[str, Sequence[str], None] = '98cacd8f2408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_item_praat_feedback', sa.Column('vowel_distortion_feedback', sa.Text(), nullable=True))
    op.add_column('training_item_praat_feedback', sa.Column('sound_stability_feedback', sa.Text(), nullable=True))
    op.add_column('training_item_praat_feedback', sa.Column('voice_clarity_feedback', sa.Text(), nullable=True))
    op.add_column('training_item_praat_feedback', sa.Column('voice_health_feedback', sa.Text(), nullable=True))
    op.add_column('training_item_praat_feedback', sa.Column('overall_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_item_praat_feedback', 'overall_feedback')
    op.drop_column('training_item_praat_feedback', 'voice_health_feedback')
    op.drop_column('training_item_praat_feedback', 'voice_clarity_feedback')
    op.drop_column('training_item_praat_feedback', 'sound_stability_feedback')
    op.drop_column('training_item_praat_feedback', 'vowel_distortion_feedback')
    # ### end Alembic commands ###
