"""init

Revision ID: d904eb67c9b4
Revises: 
Create Date: 2025-11-21 01:35:17.887349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd904eb67c9b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_session_praat_feedback_ai_model_id'), table_name='train_session_praat_feedback')
    op.drop_index(op.f('ix_train_session_praat_feedback_session_praat_result_id'), table_name='train_session_praat_feedback')
    op.drop_table('train_session_praat_feedback')
    op.drop_index(op.f('ix_train_item_praat_feedback_ai_model_id'), table_name='train_item_praat_feedback')
    op.drop_index(op.f('ix_train_item_praat_feedback_praat_features_id'), table_name='train_item_praat_feedback')
    op.drop_table('train_item_praat_feedback')
    op.drop_index(op.f('ix_train_words_word'), table_name='train_words')
    op.drop_table('train_words')
    op.drop_index(op.f('ix_train_sentences_sentence'), table_name='train_sentences')
    op.drop_table('train_sentences')
    op.drop_index(op.f('ix_training_sessions_user_id_training_date'), table_name='training_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_training_sessions_user_id_training_date'), 'training_sessions', ['user_id', 'training_date'], unique=False)
    op.create_table('train_sentences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sentence', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('train_sentences_pkey'))
    )
    op.create_index(op.f('ix_train_sentences_sentence'), 'train_sentences', ['sentence'], unique=True)
    op.create_table('train_words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('train_words_pkey'))
    )
    op.create_index(op.f('ix_train_words_word'), 'train_words', ['word'], unique=True)
    op.create_table('train_item_praat_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('praat_features_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('item_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('train_item_praat_feedback_pkey'))
    )
    op.create_index(op.f('ix_train_item_praat_feedback_praat_features_id'), 'train_item_praat_feedback', ['praat_features_id'], unique=False)
    op.create_index(op.f('ix_train_item_praat_feedback_ai_model_id'), 'train_item_praat_feedback', ['ai_model_id'], unique=False)
    op.create_table('train_session_praat_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_praat_result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ai_model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('train_session_praat_feedback_pkey'))
    )
    op.create_index(op.f('ix_train_session_praat_feedback_session_praat_result_id'), 'train_session_praat_feedback', ['session_praat_result_id'], unique=False)
    op.create_index(op.f('ix_train_session_praat_feedback_ai_model_id'), 'train_session_praat_feedback', ['ai_model_id'], unique=False)
    # ### end Alembic commands ###
