"""upgrade_user_table

Revision ID: e8f57ca4c4e0
Revises: 29d0916d7bf5
Create Date: 2025-10-24 09:58:45.293680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e8f57ca4c4e0'
down_revision: Union[str, Sequence[str], None] = '29d0916d7bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
