"""praat_relationship-fix

Revision ID: edd52e13841e
Revises: 38c5401db7fb
Create Date: 2025-11-05 16:53:16.302292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'edd52e13841e'
down_revision: Union[str, Sequence[str], None] = '38c5401db7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praat_features', sa.Column('lh_ratio_mean_db', sa.Float(), nullable=True))
    op.add_column('praat_features', sa.Column('lh_ratio_sd_db', sa.Float(), nullable=True))
    op.add_column('praat_features', sa.Column('f1', sa.Float(), nullable=True))
    op.add_column('praat_features', sa.Column('f2', sa.Float(), nullable=True))
    op.add_column('praat_features', sa.Column('intensity_mean', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('praat_features', 'intensity_mean')
    op.drop_column('praat_features', 'f2')
    op.drop_column('praat_features', 'f1')
    op.drop_column('praat_features', 'lh_ratio_sd_db')
    op.drop_column('praat_features', 'lh_ratio_mean_db')
    # ### end Alembic commands ###
