"""modified training_item_praat_feedback table

Revision ID: fbc2d3cfc97b
Revises: b249ba5637cf
Create Date: 2025-11-14 12:27:15.140372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fbc2d3cfc97b'
down_revision: Union[str, Sequence[str], None] = 'b249ba5637cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_item_praat_feedback', sa.Column('item_feedback', sa.Text(), nullable=True))
    op.drop_column('train_item_praat_feedback', 'voice_health_feedback')
    op.drop_column('train_item_praat_feedback', 'vowel_distortion_feedback')
    op.drop_column('train_item_praat_feedback', 'overall_feedback')
    op.drop_column('train_item_praat_feedback', 'sound_stability_feedback')
    op.drop_column('train_item_praat_feedback', 'voice_clarity_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_item_praat_feedback', sa.Column('voice_clarity_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('train_item_praat_feedback', sa.Column('sound_stability_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('train_item_praat_feedback', sa.Column('overall_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('train_item_praat_feedback', sa.Column('vowel_distortion_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('train_item_praat_feedback', sa.Column('voice_health_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('train_item_praat_feedback', 'item_feedback')
    # ### end Alembic commands ###
