"""발화 연습 진행 상태 관련 테이블 단어/문장으로 분리

Revision ID: fc995f696348
Revises: 793880e8f7d2
Create Date: 2025-10-24 20:36:59.596204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fc995f696348'
down_revision: Union[str, Sequence[str], None] = '793880e8f7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
